# Generated by Django 3.2.13 on 2022-10-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allgoods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('quality', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
        ),
    ]
