# Generated by Django 3.2.13 on 2022-10-31 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0004_allgoods_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allgoods',
            name='num',
        ),
    ]
