# Generated by Django 3.2.13 on 2022-10-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0005_remove_allgoods_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='allcart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('quality', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
        ),
    ]
