# Generated by Django 3.2.13 on 2022-10-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0007_allcart_gid'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcart',
            name='paid',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
