# Generated by Django 3.2.13 on 2022-11-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0010_alluser_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='allgoods',
            name='goodgood',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
