# Generated by Django 3.2.13 on 2022-11-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0011_allgoods_goodgood'),
    ]

    operations = [
        migrations.CreateModel(
            name='goodgood',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=10)),
                ('gid', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('did', models.CharField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='allgoods',
            name='goodgood',
        ),
    ]
