# Generated by Django 3.2.13 on 2022-11-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0012_auto_20221104_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='allgoods',
            name='goodnum',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='goodgood',
            name='did',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
